swagger: "2.0"
info:
  title: "JSON Ingester"
  description: "Receive JSON files, transform and load them."
  version: "1.0.0"

host: "{{PROJECT_ID}}.appspot.com"
schemes:
  - "https"
paths:
  "/dummy":
    get:
      description: "Dummy for testing."
      operationId: "dummy"
      parameters:
        -
          name: val
          in: query
          required: true
          type: string
      responses:
        200:
          description: "Success."
          schema:
            type: string
        400:
          description: "The IATA code is invalid or missing."
  "/upload":
    post:
      summary: "ETL JSON file."
      operationId: "upload"
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: file_upload
          type: file
      responses:
        200:
          description: "File uploaded."
          schema:
            type: string
        400:
          description: "Error during file upload."
